; MB8ART Basic Example
; Simple demonstration of the MB8ART temperature/relay sensor library.

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -Werror=unused-result
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
lib_deps =
    symlink://../..
    https://github.com/packerlschupfer/ESP32-ModbusDevice.git
    https://github.com/packerlschupfer/ESP32-MutexGuard.git
    https://github.com/packerlschupfer/ESP32-IDeviceInstance.git
    https://github.com/packerlschupfer/esp32ModbusRTU.git#fix/fc2-bytecount
